# Generated by Django 5.0.1 on 2024-01-17 10:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('title_2', models.CharField(blank=True, max_length=100, null=True)),
                ('description_one', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('about_avatar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Google Drive Image Id')),
            ],
            options={
                'verbose_name_plural': 'About Me Section',
            },
        ),
        migrations.CreateModel(
            name='ServicesOffred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_image', models.CharField(blank=True, max_length=100, null=True, verbose_name='Google Drive Image Id')),
                ('service_name', models.CharField(blank=True, max_length=40, null=True)),
                ('shadow_icon', models.CharField(blank=True, max_length=40, null=True)),
                ('service_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Services Section',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(blank=True, max_length=30, verbose_name='Introduction')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True, default='')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars')),
                ('resume_link', models.URLField(blank=True, null=True)),
                ('hire_me', models.CharField(default='Hire Me', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Heros Sec',
            },
        ),
    ]
