# Generated by Django 5.0.1 on 2024-01-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesOffered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_image', models.ImageField(upload_to='services')),
                ('service_name', models.CharField(blank=True, max_length=40, null=True)),
                ('shadow_icon', models.CharField(blank=True, max_length=40, null=True)),
                ('service_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Services Section',
            },
        ),
        migrations.DeleteModel(
            name='ServicesOffred',
        ),
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name_plural': 'User Section'},
        ),
    ]
