# Generated by Django 5.0.1 on 2024-01-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_servicesoffered_delete_servicesoffred_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='description_one',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
