# Generated by Django 5.0.1 on 2024-01-17 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_languagesicons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LanguagesIcons',
            new_name='LanguagesSkills',
        ),
    ]
