# Generated by Django 5.0.1 on 2024-01-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_project_alter_languagesskills_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=90, null=True, verbose_name='Icon (eg: fa -fa-twitter)')),
                ('contact_info', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Info (eg: johndoe2@gmail.com)')),
                ('social', models.CharField(blank=True, max_length=30, null=True, verbose_name='Contact Name (eg: twitter)')),
            ],
            options={
                'verbose_name_plural': 'Contacts Section',
            },
        ),
    ]
