# Generated by Django 5.0.1 on 2024-01-18 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_socialmedialinks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedialinks',
            options={'verbose_name_plural': 'Social Media Links'},
        ),
    ]
