# Generated by Django 5.0.1 on 2024-01-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_socialmedialinks_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
