# Generated by Django 5.0.1 on 2024-02-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_userdetails_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
