# Generated by Django 5.0.1 on 2024-02-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_userdetails_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='about_avatar',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='title',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='title_2',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='hire_me',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='resume_link',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='Achievements',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='Education',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='hire_me',
            field=models.CharField(default='Hire Me', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='resume',
            field=models.URLField(blank=True, null=True),
        ),
    ]
