# Generated by Django 5.0.1 on 2024-02-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_remove_aboutme_about_avatar_remove_aboutme_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='Education',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='description_one',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='Education1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='Education2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='Education3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
