# Generated by Django 5.0.1 on 2024-02-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_remove_aboutme_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='Achievements',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='Education1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='Education2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='Education3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
