# Generated by Django 5.0.1 on 2024-02-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_alter_aboutme_education1_alter_aboutme_education2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='dev_domain',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
