# Generated by Django 5.0.1 on 2024-03-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_userdetails_dev_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='hire_me',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='hire_me',
            field=models.CharField(default='Hire Me', max_length=255),
        ),
    ]
