# Generated by Django 5.0.1 on 2024-03-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_remove_userdetails_hire_me_aboutme_hire_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='hire_me',
            field=models.CharField(default='Hire Me', max_length=255, null=True),
        ),
    ]
