# Generated by Django 5.0.1 on 2024-03-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_remove_aboutme_hire_me_userdetails_hire_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='resume',
            field=models.URLField(blank=True, null=True),
        ),
    ]
