# Generated by Django 5.0.1 on 2024-03-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_userdetails_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='Education1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='Education2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='Education3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
