# Generated by Django 5.0.1 on 2024-03-04 14:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_alter_aboutme_education1_alter_aboutme_education2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='Education1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='Education2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='Education3',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
