# Generated by Django 5.0.1 on 2024-03-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_alter_aboutme_education1_alter_aboutme_education2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='Education1',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='Education2',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='Education3',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='branch',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='college',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='college_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='college_location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='country',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='grade1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='school',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='school1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='school_location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='school_location1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='stream',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='stream1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
