# Generated by Django 5.0.1 on 2024-03-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_remove_aboutme_education1_remove_aboutme_education2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='duration1',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
