# Generated by Django 5.0.1 on 2024-03-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_aboutme_duration1'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='duration2',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
