# Generated by Django 5.0.1 on 2024-03-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_aboutme_duration_aboutme_duration2'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='grade_col',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='Achievements',
            field=models.CharField(blank=True, help_text='eg: your achievements till date', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='branch',
            field=models.CharField(blank=True, help_text='eg: computer science', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='college',
            field=models.CharField(blank=True, help_text='eg: IIT Delhi', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='college_description',
            field=models.CharField(blank=True, help_text='eg: about the college', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='college_location',
            field=models.CharField(blank=True, help_text='eg: Delhi', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='country',
            field=models.CharField(blank=True, help_text='eg:India', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='duration',
            field=models.CharField(blank=True, help_text='eg: 2021-2025', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='duration1',
            field=models.CharField(blank=True, help_text='eg: 2018-2020', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='duration2',
            field=models.CharField(blank=True, help_text='eg:', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='grade',
            field=models.CharField(blank=True, help_text='eg: 77.6%', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='grade1',
            field=models.CharField(blank=True, help_text='eg:', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='resume',
            field=models.URLField(blank=True, help_text='google drive link', null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='school',
            field=models.CharField(blank=True, help_text='eg:DPS RK puram', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='school1',
            field=models.CharField(blank=True, help_text='For Matriculation Section', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='school_location',
            field=models.CharField(blank=True, help_text='eg:Delhi', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='school_location1',
            field=models.CharField(blank=True, help_text='eg:', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='stream',
            field=models.CharField(blank=True, help_text='eg:Pure Science', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='stream1',
            field=models.CharField(blank=True, help_text='eg:', max_length=300, null=True),
        ),
    ]
