# Generated by Django 5.0.1 on 2024-03-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_aboutme_grade_col_alter_aboutme_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='grade_col',
            field=models.IntegerField(blank=True, help_text='your cgpa', max_length=10, null=True),
        ),
    ]
