# Generated by Django 5.0.1 on 2024-03-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0030_remove_aboutme_grade_aboutme_grade2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='grade1',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='eg: 77.6%', max_digits=4),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='grade2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='eg:', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='grade_col',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='your cgpa', max_digits=4, null=True),
        ),
    ]
