# Generated by Django 5.0.1 on 2024-03-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0031_alter_aboutme_grade1_alter_aboutme_grade2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='grade2',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='grade',
            field=models.CharField(blank=True, help_text='eg: 77.6%', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='grade1',
            field=models.CharField(blank=True, help_text='eg:', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='grade_col',
            field=models.CharField(blank=True, help_text='your cgpa', max_length=10, null=True),
        ),
    ]
