# Generated by Django 5.0.1 on 2024-03-05 20:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0033_remove_aboutme_grade_aboutme_grade2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='Achievements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
