# Generated by Django 5.0.1 on 2024-03-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0036_achievements_remove_aboutme_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='Achievements',
            field=models.CharField(blank=True, help_text='eg: your achievements till date separate each with a comma', max_length=200, null=True),
        ),
    ]
