# Generated by Django 5.0.1 on 2024-03-05 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0037_aboutme_achievements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='achievements',
        ),
    ]
