# Generated by Django 5.0.1 on 2024-03-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0038_delete_achievements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='Achievements',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='Achievement1',
            field=models.CharField(blank=True, help_text='eg: your achievements till date', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='Achievement2',
            field=models.CharField(blank=True, help_text='eg: your achievements till date', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='Achievement3',
            field=models.CharField(blank=True, help_text='eg: your achievements till date', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='Achievement4',
            field=models.CharField(blank=True, help_text='eg: your achievements till date', max_length=200, null=True),
        ),
    ]
