# Generated by Django 5.0.1 on 2024-03-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0042_contactme_delete_mycontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMe',
        ),
    ]
