# Generated by Django 5.0.1 on 2024-03-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0043_delete_contactme'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
