# Generated by Django 5.0.1 on 2024-03-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0044_userdetails_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='uploads')),
            ],
        ),
        migrations.AlterField(
            model_name='languagesskills',
            name='icon',
            field=models.CharField(blank=True, max_length=1000, verbose_name='language Icon Image:(icons8.com)'),
        ),
    ]
