# Generated by Django 5.0.1 on 2024-03-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0045_projectphotos_alter_languagesskills_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectphotos',
            name='image',
        ),
        migrations.AddField(
            model_name='projectphotos',
            name='image1',
            field=models.ImageField(null=True, upload_to='project', verbose_name='1'),
        ),
        migrations.AddField(
            model_name='projectphotos',
            name='image2',
            field=models.ImageField(null=True, upload_to='project', verbose_name='2'),
        ),
        migrations.AddField(
            model_name='projectphotos',
            name='image3',
            field=models.ImageField(null=True, upload_to='project', verbose_name='3'),
        ),
        migrations.AddField(
            model_name='projectphotos',
            name='image4',
            field=models.ImageField(null=True, upload_to='project', verbose_name='4'),
        ),
    ]
