# Generated by Django 5.0.1 on 2024-03-15 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0046_remove_projectphotos_image_projectphotos_image1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectphotos',
            options={'verbose_name_plural': 'Project Photos'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='Project_Image',
        ),
        migrations.RemoveField(
            model_name='projectphotos',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='projectphotos',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='projectphotos',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='projectphotos',
            name='image4',
        ),
        migrations.AddField(
            model_name='projectphotos',
            name='Project_Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='projectphotos',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='portfolio.project'),
        ),
    ]
